spring.application.name=springSecurity
spring.datasource.url=jdbc:postgresql://localhost:5432/security_db
spring.datasource.username=postgres
spring.datasource.password=Temp@123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



#Auth Settings
app-jwt-expiration-milliseconds=604800000
app-jwt-secret=FaSwA9tkVQdmhdFLRFh7Bh1i/Tfrg51fJhtc1ioWQlIsONWBE3z7BXxt5FwIEf5OvlLhRqwvQxWNQNzgK/fQpQ==